"""GCP MITRE ATT&CK technique indicator library following 05-MAPPING-AGENT.md design.

This library maps GCP audit log methods, keywords, and patterns to MITRE techniques.
Based on MITRE ATT&CK v14.1 Cloud Matrix for GCP.
"""

from dataclasses import dataclass


@dataclass
class GCPTechniqueIndicator:
    """Indicators for a MITRE technique specific to GCP."""

    technique_id: str
    technique_name: str
    tactic_id: str
    tactic_name: str

    # GCP audit log method names that indicate this technique
    audit_log_methods: list[str]

    # Keywords in detection names/descriptions
    keywords: list[str]

    # GCP services relevant to this technique
    gcp_services: list[str]

    # Log filter patterns (for Cloud Logging queries)
    log_patterns: list[str]

    # Base confidence for pattern match
    base_confidence: float = 0.7

    # Priority for gap analysis (1=critical, 4=low)
    priority: int = 2


# Discovery - TA0007
GCP_DISCOVERY_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1526",
        technique_name="Cloud Service Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.instances.list",
            "compute.zones.list",
            "compute.regions.list",
            "storage.buckets.list",
            "sqladmin.instances.list",
            "cloudfunctions.functions.list",
            "container.clusters.list",
            "run.services.list",
            "iam.roles.list",
            "iam.serviceAccounts.list",
            "resourcemanager.projects.list",
        ],
        keywords=["discovery", "enumerate", "list", "describe", "inventory", "scan"],
        gcp_services=["compute", "storage", "cloudsql", "cloudfunctions", "gke", "iam"],
        log_patterns=[r"\.list$", r"\.get$", r"describe", r"inventory"],
        base_confidence=0.65,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1580",
        technique_name="Cloud Infrastructure Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.networks.list",
            "compute.subnetworks.list",
            "compute.firewalls.list",
            "compute.routes.list",
            "compute.vpnTunnels.list",
            "dns.managedZones.list",
        ],
        keywords=["network", "vpc", "firewall", "subnet", "infrastructure", "route"],
        gcp_services=["compute", "dns", "vpc"],
        log_patterns=[r"network", r"firewall", r"subnet", r"route"],
        base_confidence=0.65,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1619",
        technique_name="Cloud Storage Object Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "storage.buckets.list",
            "storage.objects.list",
            "storage.buckets.get",
            "storage.buckets.getIamPolicy",
        ],
        keywords=["bucket", "storage", "object", "gcs", "blob"],
        gcp_services=["storage"],
        log_patterns=[r"bucket", r"storage", r"object"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1087.004",
        technique_name="Account Discovery: Cloud Account",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "iam.serviceAccounts.list",
            "iam.serviceAccounts.get",
            "cloudidentity.groups.list",
            "cloudidentity.memberships.list",
            "admin.directory.users.list",
            "admin.directory.groups.list",
        ],
        keywords=["user", "account", "identity", "member", "group", "enumerate"],
        gcp_services=["iam", "cloudidentity", "admin"],
        log_patterns=[r"user", r"account", r"identity", r"member"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1069.003",
        technique_name="Permission Groups Discovery: Cloud Groups",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "cloudidentity.groups.list",
            "cloudidentity.groups.get",
            "cloudidentity.memberships.list",
            "admin.directory.groups.list",
            "admin.directory.groups.get",
        ],
        keywords=["group", "membership", "member", "role", "permission"],
        gcp_services=["cloudidentity", "admin", "iam"],
        log_patterns=[r"group", r"membership", r"permission"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1538",
        technique_name="Cloud Service Dashboard",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "monitoring.dashboards.list",
            "monitoring.dashboards.get",
            "cloudasset.assets.searchAll",
            "cloudasset.assets.list",
        ],
        keywords=["dashboard", "console", "portal", "gui", "monitoring"],
        gcp_services=["monitoring", "cloudasset", "console"],
        log_patterns=[r"dashboard", r"console", r"portal"],
        base_confidence=0.6,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1613",
        technique_name="Container and Resource Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "container.clusters.list",
            "container.clusters.get",
            "container.pods.list",
            "container.namespaces.list",
            "run.services.list",
            "artifactregistry.repositories.list",
        ],
        keywords=["container", "kubernetes", "k8s", "gke", "pod", "namespace", "docker"],
        gcp_services=["container", "run", "artifactregistry"],
        log_patterns=[r"container", r"kubernetes", r"pod", r"namespace"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1040",
        technique_name="Network Sniffing",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.packetMirrorings.list",
            "compute.packetMirrorings.get",
            "vpcaccess.connectors.list",
        ],
        keywords=["packet", "mirror", "sniff", "capture", "traffic", "network"],
        gcp_services=["compute", "vpcaccess"],
        log_patterns=[r"packet", r"mirror", r"sniff", r"capture"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1046",
        technique_name="Network Service Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.forwardingRules.list",
            "compute.targetPools.list",
            "compute.backendServices.list",
            "compute.urlMaps.list",
            "dns.resourceRecordSets.list",
        ],
        keywords=["port", "scan", "service", "endpoint", "load balancer", "dns"],
        gcp_services=["compute", "dns"],
        log_patterns=[r"port", r"scan", r"service", r"endpoint"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1018",
        technique_name="Remote System Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.instances.list",
            "compute.instances.get",
            "compute.instanceGroups.list",
            "compute.instanceTemplates.list",
        ],
        keywords=["instance", "vm", "virtual machine", "remote", "host"],
        gcp_services=["compute"],
        log_patterns=[r"instance", r"vm", r"host"],
        base_confidence=0.6,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1518",
        technique_name="Software Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "osconfig.patchJobs.list",
            "osconfig.inventories.list",
            "osconfig.vulnerabilityReports.list",
            "containeranalysis.occurrences.list",
        ],
        keywords=["software", "package", "inventory", "installed", "vulnerability"],
        gcp_services=["osconfig", "containeranalysis"],
        log_patterns=[r"software", r"package", r"inventory"],
        base_confidence=0.6,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1082",
        technique_name="System Information Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.instances.get",
            "compute.machineTypes.list",
            "compute.zones.list",
            "resourcemanager.projects.get",
        ],
        keywords=["system", "info", "machine", "type", "zone", "region"],
        gcp_services=["compute", "resourcemanager"],
        log_patterns=[r"system", r"info", r"machine", r"type"],
        base_confidence=0.6,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1614.001",
        technique_name="System Location Discovery: System Language Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.instances.get",
            "resourcemanager.projects.get",
        ],
        keywords=["location", "language", "locale", "region", "zone"],
        gcp_services=["compute", "resourcemanager"],
        log_patterns=[r"location", r"language", r"locale"],
        base_confidence=0.55,
        priority=4,
    ),
    GCPTechniqueIndicator(
        technique_id="T1016",
        technique_name="System Network Configuration Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.networks.get",
            "compute.subnetworks.get",
            "compute.addresses.list",
            "compute.firewalls.get",
            "dns.managedZones.get",
        ],
        keywords=["network", "config", "ip", "address", "dns", "firewall"],
        gcp_services=["compute", "dns"],
        log_patterns=[r"network", r"config", r"ip", r"address"],
        base_confidence=0.6,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1049",
        technique_name="System Network Connections Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        audit_log_methods=[
            "compute.interconnects.list",
            "compute.vpnGateways.list",
            "compute.vpnTunnels.list",
            "compute.routers.list",
        ],
        keywords=["connection", "interconnect", "vpn", "tunnel", "peering"],
        gcp_services=["compute"],
        log_patterns=[r"connection", r"interconnect", r"vpn", r"tunnel"],
        base_confidence=0.65,
        priority=3,
    ),
]

# Initial Access - TA0001
GCP_INITIAL_ACCESS_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1078.004",
        technique_name="Valid Accounts: Cloud Accounts",
        tactic_id="TA0001",
        tactic_name="Initial Access",
        audit_log_methods=[
            "google.login.LoginService.loginSuccess",
            "google.login.LoginService.loginFailure",
            "iam.serviceAccounts.actAs",
            "iam.serviceAccounts.getAccessToken",
            "iam.serviceAccounts.signBlob",
            "iam.serviceAccounts.signJwt",
            "sts.googleapis.com.GenerateAccessToken",
        ],
        keywords=[
            "login", "signin", "authentication", "console", "impersonate",
            "credential", "mfa", "2fa", "service account", "actAs",
        ],
        gcp_services=["iam", "sts", "cloudidentity"],
        log_patterns=[r"login", r"signin", r"actAs", r"impersonate", r"credential"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1199",
        technique_name="Trusted Relationship",
        tactic_id="TA0001",
        tactic_name="Initial Access",
        audit_log_methods=[
            "iam.serviceAccounts.actAs",
            "resourcemanager.projects.setIamPolicy",
            "resourcemanager.organizations.setIamPolicy",
            "iam.roles.create",
        ],
        keywords=["cross-project", "trust", "external", "third-party", "partner", "domain"],
        gcp_services=["iam", "resourcemanager"],
        log_patterns=[r"cross.?project", r"trust", r"external", r"domain.*wide"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1190",
        technique_name="Exploit Public-Facing Application",
        tactic_id="TA0001",
        tactic_name="Initial Access",
        audit_log_methods=[
            "cloudfunctions.functions.call",
            "run.services.call",
            "appengine.apps.services.versions.instances.debug",
        ],
        keywords=["exploit", "vulnerability", "public", "exposed", "web", "api", "rce"],
        gcp_services=["cloudfunctions", "run", "appengine", "compute"],
        log_patterns=[r"exploit", r"vulnerability", r"public", r"exposed"],
        base_confidence=0.7,
        priority=1,
    ),
]

# Persistence - TA0003
GCP_PERSISTENCE_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1098",
        technique_name="Account Manipulation",
        tactic_id="TA0003",
        tactic_name="Persistence",
        audit_log_methods=[
            "iam.serviceAccounts.setIamPolicy",
            "iam.serviceAccountKeys.create",
            "iam.serviceAccountKeys.delete",
            "resourcemanager.projects.setIamPolicy",
            "cloudfunctions.functions.setIamPolicy",
            "run.services.setIamPolicy",
        ],
        keywords=[
            "account", "manipulation", "modify", "policy", "permission",
            "iam", "binding", "member", "role",
        ],
        gcp_services=["iam", "resourcemanager"],
        log_patterns=[r"setIamPolicy", r"iam", r"binding", r"permission"],
        base_confidence=0.8,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1098.001",
        technique_name="Account Manipulation: Additional Cloud Credentials",
        tactic_id="TA0003",
        tactic_name="Persistence",
        audit_log_methods=[
            "iam.serviceAccountKeys.create",
            "iam.serviceAccountKeys.upload",
            "secretmanager.versions.add",
        ],
        keywords=[
            "service account key", "credential", "api key", "new key",
            "create key", "json key", "p12 key",
        ],
        gcp_services=["iam", "secretmanager"],
        log_patterns=[r"serviceAccountKey", r"create.*key", r"credential"],
        base_confidence=0.85,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1098.003",
        technique_name="Account Manipulation: Additional Cloud Roles",
        tactic_id="TA0003",
        tactic_name="Persistence",
        audit_log_methods=[
            "iam.roles.create",
            "iam.roles.update",
            "iam.roles.undelete",
            "resourcemanager.projects.setIamPolicy",
            "resourcemanager.folders.setIamPolicy",
            "resourcemanager.organizations.setIamPolicy",
        ],
        keywords=["role", "custom role", "permission", "privilege", "admin", "owner"],
        gcp_services=["iam", "resourcemanager"],
        log_patterns=[r"roles?\.", r"setIamPolicy", r"privilege"],
        base_confidence=0.8,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1136.003",
        technique_name="Create Account: Cloud Account",
        tactic_id="TA0003",
        tactic_name="Persistence",
        audit_log_methods=[
            "iam.serviceAccounts.create",
            "cloudidentity.groups.create",
            "cloudidentity.memberships.create",
        ],
        keywords=["create user", "new user", "service account", "create account"],
        gcp_services=["iam", "cloudidentity"],
        log_patterns=[r"create.*account", r"serviceAccounts\.create"],
        base_confidence=0.8,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1525",
        technique_name="Implant Internal Image",
        tactic_id="TA0003",
        tactic_name="Persistence",
        audit_log_methods=[
            "compute.images.create",
            "compute.images.insert",
            "artifactregistry.repositories.uploadArtifact",
            "containeranalysis.occurrences.create",
        ],
        keywords=["image", "container", "artifact", "registry", "gcr", "docker"],
        gcp_services=["compute", "artifactregistry", "containerregistry"],
        log_patterns=[r"image", r"container", r"artifact", r"registry"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1556.006",
        technique_name="Modify Authentication Process: Multi-Factor Authentication",
        tactic_id="TA0003",
        tactic_name="Persistence",
        audit_log_methods=[
            "admin.directory.users.update",
            "cloudidentity.devices.delete",
            "securitycenter.organizationSettings.update",
        ],
        keywords=["mfa", "2fa", "two-factor", "authentication", "disable", "bypass"],
        gcp_services=["cloudidentity", "admin", "securitycenter"],
        log_patterns=[r"mfa", r"2fa", r"authentication", r"factor"],
        base_confidence=0.85,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1053.007",
        technique_name="Scheduled Task/Job: Container Orchestration Job",
        tactic_id="TA0003",
        tactic_name="Persistence",
        audit_log_methods=[
            "scheduler.jobs.create",
            "scheduler.jobs.update",
            "workflows.workflows.create",
            "batch.jobs.create",
        ],
        keywords=["schedule", "cron", "job", "task", "workflow", "periodic"],
        gcp_services=["scheduler", "workflows", "batch"],
        log_patterns=[r"schedule", r"cron", r"job", r"periodic"],
        base_confidence=0.75,
        priority=2,
    ),
]

# Privilege Escalation - TA0004
GCP_PRIVILEGE_ESCALATION_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1548.005",
        technique_name="Abuse Elevation Control: Temporary Elevated Cloud Access",
        tactic_id="TA0004",
        tactic_name="Privilege Escalation",
        audit_log_methods=[
            "iam.serviceAccounts.actAs",
            "iam.serviceAccounts.getAccessToken",
            "sts.googleapis.com.GenerateAccessToken",
        ],
        keywords=["elevate", "escalate", "privilege", "admin", "temporary", "impersonate"],
        gcp_services=["iam", "sts"],
        log_patterns=[r"escalat", r"privilege", r"elevat", r"impersonate"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1078.004",
        technique_name="Valid Accounts: Cloud Accounts",
        tactic_id="TA0004",
        tactic_name="Privilege Escalation",
        audit_log_methods=[
            "iam.serviceAccounts.actAs",
            "iam.serviceAccounts.getAccessToken",
            "resourcemanager.projects.setIamPolicy",
        ],
        keywords=["impersonate", "privilege", "elevate", "admin", "owner"],
        gcp_services=["iam", "resourcemanager"],
        log_patterns=[r"impersonate", r"privilege", r"elevate"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1098.003",
        technique_name="Account Manipulation: Additional Cloud Roles",
        tactic_id="TA0004",
        tactic_name="Privilege Escalation",
        audit_log_methods=[
            "iam.roles.create",
            "iam.roles.update",
            "resourcemanager.projects.setIamPolicy",
            "resourcemanager.organizations.setIamPolicy",
        ],
        keywords=["role", "permission", "privilege", "admin", "owner", "escalate"],
        gcp_services=["iam", "resourcemanager"],
        log_patterns=[r"role", r"permission", r"privilege", r"escalat"],
        base_confidence=0.8,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1068",
        technique_name="Exploitation for Privilege Escalation",
        tactic_id="TA0004",
        tactic_name="Privilege Escalation",
        audit_log_methods=[
            "compute.instances.setMetadata",
            "compute.instances.setServiceAccount",
            "cloudfunctions.functions.update",
        ],
        keywords=["exploit", "vulnerability", "cve", "privilege", "escalation"],
        gcp_services=["compute", "cloudfunctions", "run"],
        log_patterns=[r"exploit", r"vulnerability", r"cve"],
        base_confidence=0.7,
        priority=1,
    ),
]

# Defense Evasion - TA0005
GCP_DEFENSE_EVASION_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1562.008",
        technique_name="Impair Defenses: Disable Cloud Logs",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "logging.sinks.delete",
            "logging.exclusions.create",
            "logging.logMetrics.delete",
            "logging.logs.delete",
            "securitycenter.sources.delete",
        ],
        keywords=["disable", "stop", "delete", "logging", "audit", "sink", "exclusion"],
        gcp_services=["logging", "securitycenter"],
        log_patterns=[r"delete.*log", r"disable.*log", r"exclusion"],
        base_confidence=0.85,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1578.002",
        technique_name="Modify Cloud Compute Infrastructure: Create Snapshot",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "compute.snapshots.create",
            "compute.disks.createSnapshot",
            "sqladmin.backupRuns.insert",
        ],
        keywords=["snapshot", "backup", "copy", "disk"],
        gcp_services=["compute", "sqladmin"],
        log_patterns=[r"snapshot", r"backup"],
        base_confidence=0.6,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1535",
        technique_name="Unused/Unsupported Cloud Regions",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[],
        keywords=["region", "geographic", "unused", "uncommon", "location"],
        gcp_services=["compute", "cloudfunctions", "run"],
        log_patterns=[r"region", r"location"],
        base_confidence=0.5,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1578.001",
        technique_name="Modify Cloud Compute Infrastructure: Create Cloud Instance",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "compute.instances.insert",
            "compute.instances.create",
            "compute.instanceTemplates.insert",
        ],
        keywords=["instance", "vm", "create", "new", "compute"],
        gcp_services=["compute"],
        log_patterns=[r"instance.*insert", r"instance.*create"],
        base_confidence=0.55,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1578.003",
        technique_name="Modify Cloud Compute Infrastructure: Delete Cloud Instance",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "compute.instances.delete",
            "compute.instanceGroups.delete",
        ],
        keywords=["delete", "instance", "vm", "terminate", "destroy"],
        gcp_services=["compute"],
        log_patterns=[r"instance.*delete", r"terminate"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1578.004",
        technique_name="Modify Cloud Compute Infrastructure: Revert Cloud Instance",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "compute.instances.reset",
            "compute.instances.stop",
            "compute.instances.start",
            "compute.disks.resize",
        ],
        keywords=["revert", "reset", "restore", "rollback", "snapshot"],
        gcp_services=["compute"],
        log_patterns=[r"reset", r"revert", r"restore", r"rollback"],
        base_confidence=0.6,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1562.001",
        technique_name="Impair Defenses: Disable or Modify Tools",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "securitycenter.organizationSettings.update",
            "securitycenter.sources.delete",
            "binaryauthorization.policy.update",
        ],
        keywords=["disable", "security", "defense", "modify", "tool", "agent"],
        gcp_services=["securitycenter", "binaryauthorization"],
        log_patterns=[r"disable", r"security", r"defense"],
        base_confidence=0.8,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1070.004",
        technique_name="Indicator Removal: File Deletion",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "storage.objects.delete",
            "compute.instances.deleteAccessConfig",
        ],
        keywords=["delete", "remove", "clean", "wipe", "erase"],
        gcp_services=["storage", "compute"],
        log_patterns=[r"delete", r"remove", r"clean"],
        base_confidence=0.6,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1550.001",
        technique_name="Use Alternate Authentication Material: Application Access Token",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "iam.serviceAccounts.getAccessToken",
            "iam.serviceAccounts.signJwt",
            "sts.googleapis.com.GenerateAccessToken",
        ],
        keywords=["token", "alternate", "authentication", "oauth", "jwt"],
        gcp_services=["iam", "sts"],
        log_patterns=[r"token", r"jwt", r"oauth"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1078.004",
        technique_name="Valid Accounts: Cloud Accounts",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "google.login.LoginService.loginSuccess",
            "iam.serviceAccounts.actAs",
        ],
        keywords=["valid", "account", "legitimate", "authorized"],
        gcp_services=["iam", "cloudidentity"],
        log_patterns=[r"login", r"valid", r"account"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1556",
        technique_name="Modify Authentication Process",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        audit_log_methods=[
            "admin.directory.users.update",
            "cloudidentity.groups.update",
            "iam.serviceAccounts.update",
        ],
        keywords=["authentication", "modify", "sso", "saml", "oidc", "federation"],
        gcp_services=["cloudidentity", "admin", "iam"],
        log_patterns=[r"authentication", r"sso", r"saml", r"oidc"],
        base_confidence=0.75,
        priority=1,
    ),
]

# Credential Access - TA0006
GCP_CREDENTIAL_ACCESS_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1552.005",
        technique_name="Unsecured Credentials: Cloud Instance Metadata API",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[],
        keywords=["metadata", "169.254.169.254", "metadata.google.internal", "instance identity"],
        gcp_services=["compute"],
        log_patterns=[r"metadata", r"169\.254", r"instance.*identity"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1528",
        technique_name="Steal Application Access Token",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[
            "secretmanager.versions.access",
            "secretmanager.secrets.get",
            "iam.serviceAccountKeys.get",
        ],
        keywords=["secret", "token", "credential", "key", "password", "api key"],
        gcp_services=["secretmanager", "iam"],
        log_patterns=[r"secret", r"token", r"credential", r"key"],
        base_confidence=0.7,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1110",
        technique_name="Brute Force",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[
            "google.login.LoginService.loginFailure",
            "identitytoolkit.relyingparty.verifyPassword",
        ],
        keywords=["brute", "force", "password", "spray", "credential", "stuffing", "failed login"],
        gcp_services=["cloudidentity", "identitytoolkit"],
        log_patterns=[r"brute", r"force", r"failed.*login", r"spray"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1110.001",
        technique_name="Brute Force: Password Guessing",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[
            "google.login.LoginService.loginFailure",
        ],
        keywords=["password", "guess", "brute", "force", "failed", "attempt"],
        gcp_services=["cloudidentity"],
        log_patterns=[r"password", r"guess", r"failed.*login"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1110.003",
        technique_name="Brute Force: Password Spraying",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[
            "google.login.LoginService.loginFailure",
        ],
        keywords=["spray", "password", "multiple", "accounts", "common"],
        gcp_services=["cloudidentity"],
        log_patterns=[r"spray", r"multiple.*account", r"common.*password"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1110.004",
        technique_name="Brute Force: Credential Stuffing",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[
            "google.login.LoginService.loginFailure",
        ],
        keywords=["stuffing", "credential", "leaked", "breach", "reuse"],
        gcp_services=["cloudidentity"],
        log_patterns=[r"stuffing", r"credential", r"breach"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1555",
        technique_name="Credentials from Password Stores",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[
            "secretmanager.versions.access",
            "secretmanager.secrets.list",
            "secretmanager.secrets.get",
        ],
        keywords=["secret", "vault", "password", "store", "credential"],
        gcp_services=["secretmanager"],
        log_patterns=[r"secret", r"vault", r"password"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1606.002",
        technique_name="Forge Web Credentials: SAML Tokens",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[
            "iam.serviceAccounts.signJwt",
            "iam.serviceAccounts.signBlob",
            "sts.googleapis.com.GenerateAccessToken",
        ],
        keywords=["saml", "forge", "token", "federation", "sso", "identity"],
        gcp_services=["iam", "sts", "cloudidentity"],
        log_patterns=[r"saml", r"forge", r"federation", r"sso"],
        base_confidence=0.8,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1552.001",
        technique_name="Unsecured Credentials: Credentials In Files",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        audit_log_methods=[
            "storage.objects.get",
            "storage.objects.list",
        ],
        keywords=["credential", "file", "config", "key", "password", "secret"],
        gcp_services=["storage", "compute"],
        log_patterns=[r"credential", r"config", r"key", r"password"],
        base_confidence=0.65,
        priority=2,
    ),
]

# Lateral Movement - TA0008
GCP_LATERAL_MOVEMENT_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1550.001",
        technique_name="Use Alternate Authentication Material: Application Access Token",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        audit_log_methods=[
            "iam.serviceAccounts.actAs",
            "sts.googleapis.com.GenerateAccessToken",
        ],
        keywords=["cross-project", "impersonate", "lateral", "token", "actAs"],
        gcp_services=["iam", "sts"],
        log_patterns=[r"actAs", r"impersonate", r"lateral", r"cross"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1021.004",
        technique_name="Remote Services: SSH",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        audit_log_methods=[
            "compute.instances.setMetadata",
            "oslogin.sshPublicKeys.create",
            "oslogin.users.importSshPublicKey",
        ],
        keywords=["ssh", "remote", "key", "oslogin", "connect"],
        gcp_services=["compute", "oslogin"],
        log_patterns=[r"ssh", r"remote", r"oslogin"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1021.007",
        technique_name="Remote Services: Cloud Services",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        audit_log_methods=[
            "iap.tunnelInstances.accessViaIAP",
            "compute.instances.osLogin",
            "container.clusters.getCredentials",
        ],
        keywords=["iap", "tunnel", "cloud", "service", "remote", "access"],
        gcp_services=["iap", "compute", "container"],
        log_patterns=[r"iap", r"tunnel", r"remote", r"service"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1563.001",
        technique_name="Remote Service Session Hijacking: SSH Hijacking",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        audit_log_methods=[
            "oslogin.sshPublicKeys.create",
            "oslogin.users.importSshPublicKey",
            "compute.instances.setMetadata",
        ],
        keywords=["ssh", "hijack", "session", "key", "inject"],
        gcp_services=["oslogin", "compute"],
        log_patterns=[r"ssh", r"hijack", r"inject"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1072",
        technique_name="Software Deployment Tools",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        audit_log_methods=[
            "deploymentmanager.deployments.create",
            "deploymentmanager.deployments.update",
            "container.deployments.create",
            "cloudbuild.builds.create",
        ],
        keywords=["deploy", "software", "push", "distribute", "pipeline"],
        gcp_services=["deploymentmanager", "cloudbuild", "container"],
        log_patterns=[r"deploy", r"software", r"push", r"distribute"],
        base_confidence=0.65,
        priority=2,
    ),
]

# Collection - TA0009
GCP_COLLECTION_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1530",
        technique_name="Data from Cloud Storage",
        tactic_id="TA0009",
        tactic_name="Collection",
        audit_log_methods=[
            "storage.objects.get",
            "storage.objects.copy",
            "bigquery.tables.getData",
            "bigquery.jobs.query",
        ],
        keywords=["download", "exfil", "copy", "data", "gcs", "bigquery", "bucket"],
        gcp_services=["storage", "bigquery"],
        log_patterns=[r"objects\.get", r"download", r"copy", r"getData"],
        base_confidence=0.6,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1119",
        technique_name="Automated Collection",
        tactic_id="TA0009",
        tactic_name="Collection",
        audit_log_methods=[
            "scheduler.jobs.create",
            "cloudfunctions.functions.create",
            "workflows.workflows.create",
            "pubsub.subscriptions.create",
        ],
        keywords=["automated", "scheduled", "collection", "script", "batch"],
        gcp_services=["scheduler", "cloudfunctions", "workflows", "pubsub"],
        log_patterns=[r"automated", r"schedule", r"batch", r"collect"],
        base_confidence=0.6,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1213.003",
        technique_name="Data from Information Repositories: Code Repositories",
        tactic_id="TA0009",
        tactic_name="Collection",
        audit_log_methods=[
            "sourcerepo.repos.list",
            "sourcerepo.repos.get",
            "cloudbuild.builds.get",
        ],
        keywords=["repo", "repository", "code", "source", "git"],
        gcp_services=["sourcerepo", "cloudbuild"],
        log_patterns=[r"repo", r"repository", r"source", r"code"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1074.002",
        technique_name="Data Staged: Remote Data Staging",
        tactic_id="TA0009",
        tactic_name="Collection",
        audit_log_methods=[
            "storage.buckets.create",
            "storage.objects.create",
            "transfer.transferJobs.create",
        ],
        keywords=["staging", "transfer", "copy", "stage", "data"],
        gcp_services=["storage", "transfer"],
        log_patterns=[r"staging", r"transfer", r"stage"],
        base_confidence=0.6,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1560.001",
        technique_name="Archive Collected Data: Archive via Utility",
        tactic_id="TA0009",
        tactic_name="Collection",
        audit_log_methods=[
            "storage.objects.create",
            "storage.objects.compose",
        ],
        keywords=["archive", "compress", "zip", "tar", "backup"],
        gcp_services=["storage"],
        log_patterns=[r"archive", r"compress", r"zip", r"tar"],
        base_confidence=0.6,
        priority=3,
    ),
]

# Exfiltration - TA0010
GCP_EXFILTRATION_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1537",
        technique_name="Transfer Data to Cloud Account",
        tactic_id="TA0010",
        tactic_name="Exfiltration",
        audit_log_methods=[
            "storage.buckets.setIamPolicy",
            "storage.objects.setIamPolicy",
            "compute.snapshots.setIamPolicy",
            "bigquery.datasets.setIamPolicy",
        ],
        keywords=["public", "share", "external", "transfer", "exfil", "allUsers", "allAuthenticatedUsers"],
        gcp_services=["storage", "compute", "bigquery"],
        log_patterns=[r"public", r"share", r"external", r"allUsers", r"allAuthenticated"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1567.002",
        technique_name="Exfiltration Over Web Service: Exfiltration to Cloud Storage",
        tactic_id="TA0010",
        tactic_name="Exfiltration",
        audit_log_methods=[
            "storage.objects.create",
            "transfer.transferJobs.create",
            "bigquery.jobs.insert",
        ],
        keywords=["exfil", "upload", "transfer", "cloud", "storage", "export"],
        gcp_services=["storage", "transfer", "bigquery"],
        log_patterns=[r"exfil", r"upload", r"transfer", r"export"],
        base_confidence=0.7,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1048",
        technique_name="Exfiltration Over Alternative Protocol",
        tactic_id="TA0010",
        tactic_name="Exfiltration",
        audit_log_methods=[
            "dns.managedZones.create",
            "compute.firewalls.create",
            "compute.firewalls.update",
        ],
        keywords=["dns", "tunnel", "alternative", "protocol", "exfil", "covert"],
        gcp_services=["dns", "compute"],
        log_patterns=[r"dns", r"tunnel", r"alternative", r"covert"],
        base_confidence=0.7,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1567",
        technique_name="Exfiltration Over Web Service",
        tactic_id="TA0010",
        tactic_name="Exfiltration",
        audit_log_methods=[
            "cloudfunctions.functions.call",
            "run.services.call",
            "appengine.apps.services.versions.instances.debug",
        ],
        keywords=["web", "http", "api", "exfil", "external", "upload"],
        gcp_services=["cloudfunctions", "run", "appengine"],
        log_patterns=[r"web", r"http", r"api", r"external"],
        base_confidence=0.65,
        priority=2,
    ),
]

# Impact - TA0040
GCP_IMPACT_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1485",
        technique_name="Data Destruction",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "storage.buckets.delete",
            "storage.objects.delete",
            "compute.instances.delete",
            "compute.disks.delete",
            "sqladmin.instances.delete",
            "bigquery.datasets.delete",
            "bigquery.tables.delete",
        ],
        keywords=["delete", "destroy", "terminate", "remove", "wipe"],
        gcp_services=["storage", "compute", "sqladmin", "bigquery"],
        log_patterns=[r"\.delete$", r"destroy", r"terminate"],
        base_confidence=0.75,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1486",
        technique_name="Data Encrypted for Impact",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "cloudkms.cryptoKeys.create",
            "cloudkms.cryptoKeyVersions.destroy",
            "storage.buckets.update",  # For CSEK changes
        ],
        keywords=["encrypt", "kms", "key", "csek", "cmek"],
        gcp_services=["cloudkms", "storage"],
        log_patterns=[r"encrypt", r"kms", r"key"],
        base_confidence=0.6,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1496",
        technique_name="Resource Hijacking",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "compute.instances.insert",
            "compute.instances.setMachineType",
            "cloudfunctions.functions.create",
            "run.services.create",
        ],
        keywords=["crypto", "mining", "hijack", "resource", "compute", "bitcoin"],
        gcp_services=["compute", "cloudfunctions", "run"],
        log_patterns=[r"crypto", r"mining", r"unusual.*compute"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1489",
        technique_name="Service Stop",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "compute.instances.stop",
            "compute.instances.suspend",
            "run.services.delete",
            "cloudfunctions.functions.delete",
            "appengine.apps.services.delete",
            "container.clusters.delete",
        ],
        keywords=["stop", "disable", "shutdown", "terminate", "suspend"],
        gcp_services=["compute", "run", "cloudfunctions", "appengine", "container"],
        log_patterns=[r"stop", r"disable", r"shutdown", r"suspend"],
        base_confidence=0.7,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1490",
        technique_name="Inhibit System Recovery",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "compute.snapshots.delete",
            "sqladmin.backupRuns.delete",
            "compute.images.delete",
            "storage.buckets.delete",
        ],
        keywords=["backup", "snapshot", "recovery", "delete", "destroy"],
        gcp_services=["compute", "sqladmin", "storage"],
        log_patterns=[r"backup", r"snapshot", r"recovery", r"delete"],
        base_confidence=0.8,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1498",
        technique_name="Network Denial of Service",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "compute.firewalls.delete",
            "compute.firewalls.update",
            "compute.networks.delete",
        ],
        keywords=["ddos", "dos", "denial", "flood", "network", "attack"],
        gcp_services=["compute"],
        log_patterns=[r"ddos", r"dos", r"denial", r"flood"],
        base_confidence=0.7,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1499",
        technique_name="Endpoint Denial of Service",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "compute.instances.setScheduling",
            "compute.instances.setMachineType",
            "cloudfunctions.functions.update",
        ],
        keywords=["dos", "denial", "resource", "exhaust", "overload"],
        gcp_services=["compute", "cloudfunctions"],
        log_patterns=[r"dos", r"denial", r"exhaust", r"overload"],
        base_confidence=0.65,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1531",
        technique_name="Account Access Removal",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "iam.serviceAccounts.delete",
            "iam.serviceAccountKeys.delete",
            "resourcemanager.projects.setIamPolicy",
            "cloudidentity.memberships.delete",
        ],
        keywords=["remove", "delete", "access", "account", "revoke", "lockout"],
        gcp_services=["iam", "resourcemanager", "cloudidentity"],
        log_patterns=[r"remove", r"delete", r"access", r"revoke", r"lockout"],
        base_confidence=0.8,
        priority=1,
    ),
    GCPTechniqueIndicator(
        technique_id="T1565.001",
        technique_name="Data Manipulation: Stored Data Manipulation",
        tactic_id="TA0040",
        tactic_name="Impact",
        audit_log_methods=[
            "storage.objects.update",
            "storage.objects.patch",
            "bigquery.tables.update",
            "sqladmin.instances.update",
        ],
        keywords=["manipulate", "modify", "tamper", "corrupt", "alter"],
        gcp_services=["storage", "bigquery", "sqladmin"],
        log_patterns=[r"manipulate", r"modify", r"tamper", r"corrupt"],
        base_confidence=0.65,
        priority=2,
    ),
]

# Execution - TA0002
GCP_EXECUTION_TECHNIQUES = [
    GCPTechniqueIndicator(
        technique_id="T1059.009",
        technique_name="Command and Scripting Interpreter: Cloud API",
        tactic_id="TA0002",
        tactic_name="Execution",
        audit_log_methods=[
            "cloudfunctions.functions.call",
            "run.jobs.run",
            "workflows.executions.create",
            "compute.instances.setMetadata",  # Startup scripts
        ],
        keywords=["execute", "invoke", "function", "cloud run", "workflow", "script"],
        gcp_services=["cloudfunctions", "run", "workflows", "compute"],
        log_patterns=[r"invoke", r"execute", r"call", r"run"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1648",
        technique_name="Serverless Execution",
        tactic_id="TA0002",
        tactic_name="Execution",
        audit_log_methods=[
            "cloudfunctions.functions.create",
            "cloudfunctions.functions.update",
            "cloudfunctions.functions.call",
            "run.services.create",
            "run.jobs.create",
        ],
        keywords=["cloud function", "cloud run", "serverless", "function", "invoke"],
        gcp_services=["cloudfunctions", "run"],
        log_patterns=[r"function", r"serverless", r"run\."],
        base_confidence=0.75,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1204.003",
        technique_name="User Execution: Malicious Image",
        tactic_id="TA0002",
        tactic_name="Execution",
        audit_log_methods=[
            "compute.instances.insert",
            "container.clusters.create",
            "run.services.create",
            "artifactregistry.repositories.downloadArtifact",
        ],
        keywords=["image", "container", "malicious", "deploy", "docker"],
        gcp_services=["compute", "container", "run", "artifactregistry"],
        log_patterns=[r"image", r"container", r"malicious", r"deploy"],
        base_confidence=0.7,
        priority=2,
    ),
    GCPTechniqueIndicator(
        technique_id="T1106",
        technique_name="Native API",
        tactic_id="TA0002",
        tactic_name="Execution",
        audit_log_methods=[
            "compute.instances.setMetadata",
            "compute.projects.setCommonInstanceMetadata",
            "cloudfunctions.functions.call",
        ],
        keywords=["api", "native", "sdk", "gcloud", "rest"],
        gcp_services=["compute", "cloudfunctions", "run"],
        log_patterns=[r"api", r"sdk", r"native"],
        base_confidence=0.6,
        priority=3,
    ),
    GCPTechniqueIndicator(
        technique_id="T1609",
        technique_name="Container Administration Command",
        tactic_id="TA0002",
        tactic_name="Execution",
        audit_log_methods=[
            "container.clusters.getCredentials",
            "container.pods.exec",
            "container.deployments.create",
        ],
        keywords=["kubectl", "container", "exec", "admin", "command", "pod"],
        gcp_services=["container"],
        log_patterns=[r"kubectl", r"exec", r"pod", r"container"],
        base_confidence=0.75,
        priority=2,
    ),
]


# Combine all GCP technique indicators
GCP_TECHNIQUE_INDICATORS: list[GCPTechniqueIndicator] = [
    *GCP_DISCOVERY_TECHNIQUES,
    *GCP_INITIAL_ACCESS_TECHNIQUES,
    *GCP_PERSISTENCE_TECHNIQUES,
    *GCP_PRIVILEGE_ESCALATION_TECHNIQUES,
    *GCP_DEFENSE_EVASION_TECHNIQUES,
    *GCP_CREDENTIAL_ACCESS_TECHNIQUES,
    *GCP_LATERAL_MOVEMENT_TECHNIQUES,
    *GCP_COLLECTION_TECHNIQUES,
    *GCP_EXFILTRATION_TECHNIQUES,
    *GCP_IMPACT_TECHNIQUES,
    *GCP_EXECUTION_TECHNIQUES,
]

# Create lookup dictionaries for efficient access
GCP_TECHNIQUE_BY_ID: dict[str, GCPTechniqueIndicator] = {
    t.technique_id: t for t in GCP_TECHNIQUE_INDICATORS
}

GCP_TECHNIQUES_BY_TACTIC: dict[str, list[GCPTechniqueIndicator]] = {}
for t in GCP_TECHNIQUE_INDICATORS:
    if t.tactic_id not in GCP_TECHNIQUES_BY_TACTIC:
        GCP_TECHNIQUES_BY_TACTIC[t.tactic_id] = []
    GCP_TECHNIQUES_BY_TACTIC[t.tactic_id].append(t)

GCP_AUDIT_METHOD_TO_TECHNIQUES: dict[str, list[str]] = {}
for t in GCP_TECHNIQUE_INDICATORS:
    for method in t.audit_log_methods:
        if method not in GCP_AUDIT_METHOD_TO_TECHNIQUES:
            GCP_AUDIT_METHOD_TO_TECHNIQUES[method] = []
        GCP_AUDIT_METHOD_TO_TECHNIQUES[method].append(t.technique_id)
