"""MITRE ATT&CK technique indicator library following 05-MAPPING-AGENT.md design.

This library maps CloudTrail events, keywords, and patterns to MITRE techniques.
Based on MITRE ATT&CK v14.1 Cloud Matrix.
"""

from dataclasses import dataclass


@dataclass
class TechniqueIndicator:
    """Indicators for a MITRE technique."""

    technique_id: str
    technique_name: str
    tactic_id: str
    tactic_name: str

    # CloudTrail event names that indicate this technique
    cloudtrail_events: list[str]

    # Keywords in detection names/descriptions
    keywords: list[str]

    # AWS services relevant to this technique
    aws_services: list[str]

    # Log group patterns (regex)
    log_patterns: list[str]

    # Base confidence for pattern match
    base_confidence: float = 0.7

    # Priority for gap analysis (1=critical, 4=low)
    priority: int = 2


# Reconnaissance - TA0043
RECON_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1526",
        technique_name="Cloud Service Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeInstances",
            "ListBuckets",
            "DescribeDBInstances",
            "ListFunctions",
            "DescribeVpcs",
            "ListRoles",
            "GetAccountAuthorizationDetails",
        ],
        keywords=["discovery", "enumerate", "list", "describe", "inventory"],
        aws_services=["ec2", "s3", "rds", "lambda", "iam"],
        log_patterns=[r"describe", r"list", r"get.*config"],
        base_confidence=0.65,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1595.001",
        technique_name="Active Scanning: Scanning IP Blocks",
        tactic_id="TA0043",
        tactic_name="Reconnaissance",
        cloudtrail_events=[],
        keywords=["port scan", "probe", "scan", "reconnaissance"],
        aws_services=["vpc", "ec2"],
        log_patterns=[r"port.*scan", r"probe", r"recon"],
        base_confidence=0.7,
        priority=2,
    ),
]

# Execution - TA0002
EXECUTION_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1059.009",
        technique_name="Command and Scripting Interpreter: Cloud API",
        tactic_id="TA0002",
        tactic_name="Execution",
        cloudtrail_events=[
            "Invoke",
            "InvokeFunction",
            "StartExecution",
            "SendCommand",
            "RunInstances",
        ],
        keywords=["execute", "invoke", "command", "lambda", "step function", "ssm"],
        aws_services=["lambda", "stepfunctions", "ssm", "ec2"],
        log_patterns=[r"invoke", r"execute", r"command"],
        base_confidence=0.7,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1204.003",
        technique_name="User Execution: Malicious Image",
        tactic_id="TA0002",
        tactic_name="Execution",
        cloudtrail_events=[
            "RunInstances",
            "CreateFunction",
            "UpdateFunctionCode",
        ],
        keywords=["container", "image", "malicious", "ecr", "ami"],
        aws_services=["ec2", "ecr", "lambda"],
        log_patterns=[r"container", r"image", r"ami"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1648",
        technique_name="Serverless Execution",
        tactic_id="TA0002",
        tactic_name="Execution",
        cloudtrail_events=[
            "CreateFunction",
            "UpdateFunctionCode",
            "InvokeFunction",
            "CreateEventSourceMapping",
        ],
        keywords=["lambda", "serverless", "function", "invoke"],
        aws_services=["lambda", "apigateway"],
        log_patterns=[r"lambda", r"serverless", r"function"],
        base_confidence=0.75,
        priority=2,
    ),
]

# Initial Access - TA0001
INITIAL_ACCESS_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1078.004",
        technique_name="Valid Accounts: Cloud Accounts",
        tactic_id="TA0001",
        tactic_name="Initial Access",
        cloudtrail_events=[
            "ConsoleLogin",
            "AssumeRole",
            "GetSessionToken",
            "AssumeRoleWithSAML",
            "AssumeRoleWithWebIdentity",
        ],
        keywords=[
            "login",
            "signin",
            "authentication",
            "console",
            "assume",
            "credential",
            "mfa",
            # MITRE official terms for credential misuse detection
            "unauthorized",
            "unauthorised",  # UK spelling
            "access denied",
            "accessdenied",
            "suspicious",
            "anomalous",
            "unusual",
            # AWS error codes indicating credential issues (keep US spelling)
            "unauthorizedoperation",
            # CIS benchmark terminology
            "root account",
        ],
        aws_services=["sts", "signin", "iam"],
        log_patterns=[
            r"login",
            r"signin",
            r"console",
            r"assume.*role",
            r"unauthori[sz]ed",  # Match both UK and US spellings
            r"denied",
        ],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1199",
        technique_name="Trusted Relationship",
        tactic_id="TA0001",
        tactic_name="Initial Access",
        cloudtrail_events=[
            "AssumeRole",
            "CreateRole",
            "UpdateAssumeRolePolicy",
            "PutRolePolicy",
        ],
        keywords=["cross-account", "trust", "external", "third-party", "partner"],
        aws_services=["sts", "iam", "organizations"],
        log_patterns=[r"cross.?account", r"trust", r"external"],
        base_confidence=0.7,
        priority=2,
    ),
]

# Persistence - TA0003
PERSISTENCE_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1098",
        technique_name="Account Manipulation",
        tactic_id="TA0003",
        tactic_name="Persistence",
        cloudtrail_events=[
            "CreateAccessKey",
            "DeleteAccessKey",
            "UpdateAccessKey",
            "CreateLoginProfile",
            "UpdateLoginProfile",
            "DeleteLoginProfile",
            "AttachUserPolicy",
            "DetachUserPolicy",
            "AddUserToGroup",
            "RemoveUserFromGroup",
            "PutUserPolicy",
            "DeleteUserPolicy",
            "EnableMFADevice",
            "DeactivateMFADevice",
        ],
        keywords=[
            "account",
            "manipulation",
            "modify",
            "change",
            "policy",
            "permission",
            "user",
            "mfa",
            # MITRE official terms
            "privilege",
            "escalation",
            "attribute",
            "membership",
            "group",
            # CIS benchmark terminology
            "iam change",
            "policy change",
        ],
        aws_services=["iam"],
        log_patterns=[
            r"account",
            r"manipulate",
            r"modify.*user",
            r"change.*policy",
            r"privilege",
            r"escalate",
        ],
        base_confidence=0.8,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1098.001",
        technique_name="Account Manipulation: Additional Cloud Credentials",
        tactic_id="TA0003",
        tactic_name="Persistence",
        cloudtrail_events=[
            "CreateAccessKey",
            "CreateLoginProfile",
            "UpdateLoginProfile",
            "CreateServiceSpecificCredential",
            "UploadSSHPublicKey",
        ],
        keywords=[
            "access key",
            "credential",
            "api key",
            "new key",
            "create key",
            "password",
        ],
        aws_services=["iam"],
        log_patterns=[r"create.*key", r"access.?key", r"credential"],
        base_confidence=0.8,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1098.003",
        technique_name="Account Manipulation: Additional Cloud Roles",
        tactic_id="TA0003",
        tactic_name="Persistence",
        cloudtrail_events=[
            "CreateRole",
            "AttachRolePolicy",
            "PutRolePolicy",
            "UpdateAssumeRolePolicy",
            "AttachUserPolicy",
        ],
        keywords=["role", "policy", "permission", "attach", "privilege"],
        aws_services=["iam"],
        log_patterns=[r"role", r"policy", r"permission"],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1136.003",
        technique_name="Create Account: Cloud Account",
        tactic_id="TA0003",
        tactic_name="Persistence",
        cloudtrail_events=[
            "CreateUser",
            "CreateGroup",
            "AddUserToGroup",
            "InviteAccountToOrganization",
        ],
        keywords=["create user", "new user", "add user", "user creation"],
        aws_services=["iam", "organizations"],
        log_patterns=[r"create.*user", r"new.*account"],
        base_confidence=0.8,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1525",
        technique_name="Implant Internal Image",
        tactic_id="TA0003",
        tactic_name="Persistence",
        cloudtrail_events=[
            "CreateImage",
            "RegisterImage",
            "ModifyImageAttribute",
            "CopyImage",
            "PutImage",
        ],
        keywords=["ami", "image", "container", "ecr", "registry"],
        aws_services=["ec2", "ecr"],
        log_patterns=[r"image", r"ami", r"container", r"registry"],
        base_confidence=0.7,
        priority=2,
    ),
]

# Privilege Escalation - TA0004
PRIVILEGE_ESCALATION_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1548.005",
        technique_name="Abuse Elevation Control: Temporary Elevated Cloud Access",
        tactic_id="TA0004",
        tactic_name="Privilege Escalation",
        cloudtrail_events=[
            "AssumeRole",
            "GetSessionToken",
            "GetFederationToken",
        ],
        keywords=["elevate", "escalate", "privilege", "admin", "temporary"],
        aws_services=["sts", "iam"],
        log_patterns=[r"escalat", r"privilege", r"elevat"],
        base_confidence=0.7,
        priority=1,
    ),
]

# Defense Evasion - TA0005
DEFENSE_EVASION_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1562.008",
        technique_name="Impair Defenses: Disable Cloud Logs",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "StopLogging",
            "DeleteTrail",
            "UpdateTrail",
            "PutEventSelectors",
            "DeleteFlowLogs",
            "DeleteDeliveryChannel",
        ],
        keywords=[
            "disable",
            "stop",
            "delete",
            "logging",
            "trail",
            "audit",
            # MITRE official terms
            "remove",
            "impair",
            # CIS benchmark terminology
            "cloudtrail",
            "flow logs",
        ],
        aws_services=["cloudtrail", "config", "vpc"],
        log_patterns=[
            r"stop.*log",
            r"delete.*trail",
            r"disable.*log",
            r"impair",
            r"remove.*log",
        ],
        base_confidence=0.85,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1578.002",
        technique_name="Modify Cloud Compute Infrastructure: Create Snapshot",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "CreateSnapshot",
            "CopySnapshot",
            "ModifySnapshotAttribute",
            "CreateDBSnapshot",
        ],
        keywords=["snapshot", "backup", "copy"],
        aws_services=["ec2", "rds", "ebs"],
        log_patterns=[r"snapshot", r"backup"],
        base_confidence=0.6,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1535",
        technique_name="Unused/Unsupported Cloud Regions",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[],
        keywords=["region", "geographic", "unused", "uncommon"],
        aws_services=["ec2", "lambda"],
        log_patterns=[r"region"],
        base_confidence=0.5,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1578.001",
        technique_name="Modify Cloud Compute Infrastructure: Create Cloud Instance",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "RunInstances",
            "CreateLaunchTemplate",
        ],
        keywords=["instance", "ec2", "create", "new", "compute"],
        aws_services=["ec2"],
        log_patterns=[r"run.*instance", r"create.*instance"],
        base_confidence=0.55,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1578.003",
        technique_name="Modify Cloud Compute Infrastructure: Delete Cloud Instance",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "TerminateInstances",
            "DeleteLaunchTemplate",
        ],
        keywords=["delete", "instance", "terminate", "destroy"],
        aws_services=["ec2"],
        log_patterns=[r"terminate.*instance", r"delete.*instance"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1578.004",
        technique_name="Modify Cloud Compute Infrastructure: Revert Cloud Instance",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "RestoreDBInstanceFromDBSnapshot",
            "RestoreVolumeFromSnapshot",
            "RebootInstances",
            "StopInstances",
            "StartInstances",
        ],
        keywords=["revert", "reset", "restore", "rollback", "snapshot"],
        aws_services=["ec2", "rds"],
        log_patterns=[r"reset", r"revert", r"restore", r"rollback"],
        base_confidence=0.6,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1562.001",
        technique_name="Impair Defenses: Disable or Modify Tools",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "DisableSecurityHub",
            "DeleteDetector",
            "UpdateDetector",
            "DisableImportFindings",
            "DeleteMembers",
        ],
        keywords=["disable", "security", "defense", "modify", "tool", "guardduty"],
        aws_services=["guardduty", "securityhub", "inspector"],
        log_patterns=[r"disable", r"security", r"defense"],
        base_confidence=0.8,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1562.007",
        technique_name="Impair Defenses: Disable or Modify Cloud Firewall",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "AuthorizeSecurityGroupIngress",
            "AuthorizeSecurityGroupEgress",
            "RevokeSecurityGroupIngress",
            "RevokeSecurityGroupEgress",
            "CreateSecurityGroup",
            "DeleteSecurityGroup",
            "ModifySecurityGroupRules",
            "CreateNetworkAclEntry",
            "DeleteNetworkAclEntry",
            "ReplaceNetworkAclEntry",
        ],
        keywords=[
            "security group",
            "firewall",
            "nacl",
            "network acl",
            "ingress",
            "egress",
            "port",
            "ssh",
            "rdp",
            "restricted",
            "open",
            "allow",
            "inbound",
            "outbound",
        ],
        aws_services=["ec2", "vpc"],
        log_patterns=[
            r"security.?group",
            r"firewall",
            r"nacl",
            r"network.?acl",
            r"ingress",
            r"egress",
            r"port",
        ],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1070.004",
        technique_name="Indicator Removal: File Deletion",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "DeleteObject",
            "DeleteObjects",
            "DeleteBucket",
        ],
        keywords=["delete", "remove", "clean", "wipe", "erase"],
        aws_services=["s3"],
        log_patterns=[r"delete", r"remove", r"clean"],
        base_confidence=0.6,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1550.001",
        technique_name="Use Alternate Authentication Material: Application Access Token",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "AssumeRole",
            "GetSessionToken",
            "GetFederationToken",
        ],
        keywords=["token", "alternate", "authentication", "session"],
        aws_services=["sts"],
        log_patterns=[r"token", r"session", r"assume"],
        base_confidence=0.7,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1078.004",
        technique_name="Valid Accounts: Cloud Accounts",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "ConsoleLogin",
            "AssumeRole",
        ],
        keywords=[
            "valid",
            "account",
            "legitimate",
            "authorized",
            "authorised",  # UK spelling
            # MITRE official terms for credential misuse detection
            "unauthorized",
            "unauthorised",  # UK spelling
            "access denied",
            "accessdenied",
            "suspicious",
            "anomalous",
            "unusual",
            # AWS error codes (keep US spelling)
            "unauthorizedoperation",
        ],
        aws_services=["iam", "sts"],
        log_patterns=[r"login", r"valid", r"account", r"unauthori[sz]ed", r"denied"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1556",
        technique_name="Modify Authentication Process",
        tactic_id="TA0005",
        tactic_name="Defense Evasion",
        cloudtrail_events=[
            "UpdateSAMLProvider",
            "CreateSAMLProvider",
            "CreateIdentityProvider",
            "UpdateIdentityProvider",
        ],
        keywords=["authentication", "modify", "sso", "saml", "oidc", "federation"],
        aws_services=["iam"],
        log_patterns=[r"authentication", r"sso", r"saml", r"oidc"],
        base_confidence=0.75,
        priority=1,
    ),
]

# Credential Access - TA0006
CREDENTIAL_ACCESS_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1552.005",
        technique_name="Unsecured Credentials: Cloud Instance Metadata API",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        cloudtrail_events=[],
        keywords=["metadata", "imds", "169.254.169.254", "instance identity"],
        aws_services=["ec2"],
        log_patterns=[r"metadata", r"169\.254", r"imds"],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1528",
        technique_name="Steal Application Access Token",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        cloudtrail_events=[
            "GetSecretValue",
            "GetParameter",
            "GetParameters",
            "DescribeSecret",
        ],
        keywords=["secret", "token", "parameter store", "ssm", "credential"],
        aws_services=["secretsmanager", "ssm"],
        log_patterns=[r"secret", r"token", r"ssm"],
        base_confidence=0.7,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1110",
        technique_name="Brute Force",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        cloudtrail_events=[
            "ConsoleLogin",
        ],
        keywords=[
            "brute",
            "force",
            "password",
            "spray",
            "credential",
            "stuffing",
            "failed login",
            # MITRE official terms
            "guess",
            "attempt",
            # CIS benchmark terminology
            "authentication failure",
            "failed console",
            "console signin failure",
            "failed authentication",
        ],
        aws_services=["signin", "iam"],
        log_patterns=[
            r"brute",
            r"force",
            r"failed.*login",
            r"spray",
            r"failed.*auth",
            r"authentication.*fail",
        ],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1110.001",
        technique_name="Brute Force: Password Guessing",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        cloudtrail_events=[
            "ConsoleLogin",
        ],
        keywords=["password", "guess", "brute", "force", "failed", "attempt"],
        aws_services=["signin"],
        log_patterns=[r"password", r"guess", r"failed.*login"],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1110.003",
        technique_name="Brute Force: Password Spraying",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        cloudtrail_events=[
            "ConsoleLogin",
        ],
        keywords=["spray", "password", "multiple", "accounts", "common"],
        aws_services=["signin"],
        log_patterns=[r"spray", r"multiple.*account", r"common.*password"],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1555",
        technique_name="Credentials from Password Stores",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        cloudtrail_events=[
            "GetSecretValue",
            "ListSecrets",
            "DescribeSecret",
            "GetParameter",
            "GetParametersByPath",
        ],
        keywords=["secret", "vault", "password", "store", "credential"],
        aws_services=["secretsmanager", "ssm"],
        log_patterns=[r"secret", r"vault", r"password"],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1606.002",
        technique_name="Forge Web Credentials: SAML Tokens",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        cloudtrail_events=[
            "AssumeRoleWithSAML",
            "UpdateSAMLProvider",
            "CreateSAMLProvider",
        ],
        keywords=["saml", "forge", "token", "federation", "sso", "identity"],
        aws_services=["iam", "sts"],
        log_patterns=[r"saml", r"forge", r"federation", r"sso"],
        base_confidence=0.8,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1552.001",
        technique_name="Unsecured Credentials: Credentials In Files",
        tactic_id="TA0006",
        tactic_name="Credential Access",
        cloudtrail_events=[
            "GetObject",
            "ListObjects",
        ],
        keywords=["credential", "file", "config", "key", "password", "secret"],
        aws_services=["s3", "ec2"],
        log_patterns=[r"credential", r"config", r"key", r"password"],
        base_confidence=0.65,
        priority=2,
    ),
]

# Discovery - TA0007
DISCOVERY_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1580",
        technique_name="Cloud Infrastructure Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeInstances",
            "DescribeSecurityGroups",
            "DescribeSubnets",
            "DescribeVpcs",
            "DescribeVolumes",
        ],
        keywords=["infrastructure", "network", "vpc", "security group", "subnet"],
        aws_services=["ec2", "vpc"],
        log_patterns=[r"describe", r"infrastructure"],
        base_confidence=0.65,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1619",
        technique_name="Cloud Storage Object Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "ListBuckets",
            "ListObjects",
            "ListObjectsV2",
            "GetBucketLocation",
            "GetBucketPolicy",
        ],
        keywords=["s3", "bucket", "storage", "object", "list"],
        aws_services=["s3"],
        log_patterns=[r"bucket", r"s3", r"storage"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1087.004",
        technique_name="Account Discovery: Cloud Account",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "ListUsers",
            "ListRoles",
            "ListGroups",
            "GetUser",
            "GetRole",
            "GetAccountAuthorizationDetails",
            "ListAccountAliases",
        ],
        keywords=["user", "account", "identity", "member", "group", "enumerate"],
        aws_services=["iam", "organizations"],
        log_patterns=[r"user", r"account", r"identity", r"member"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1069.003",
        technique_name="Permission Groups Discovery: Cloud Groups",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "ListGroups",
            "ListGroupsForUser",
            "GetGroup",
            "ListGroupPolicies",
            "ListAttachedGroupPolicies",
        ],
        keywords=["group", "membership", "member", "role", "permission"],
        aws_services=["iam"],
        log_patterns=[r"group", r"membership", r"permission"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1538",
        technique_name="Cloud Service Dashboard",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeDashboards",
            "GetDashboard",
            "ListDashboards",
            "DescribeAlarms",
        ],
        keywords=["dashboard", "console", "portal", "gui", "monitoring"],
        aws_services=["cloudwatch", "console"],
        log_patterns=[r"dashboard", r"console", r"portal"],
        base_confidence=0.6,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1613",
        technique_name="Container and Resource Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeClusters",
            "ListClusters",
            "DescribeServices",
            "ListServices",
            "DescribeTaskDefinition",
            "ListTaskDefinitions",
            "DescribeRepositories",
        ],
        keywords=["container", "kubernetes", "ecs", "eks", "pod", "fargate", "docker"],
        aws_services=["ecs", "eks", "ecr"],
        log_patterns=[r"container", r"kubernetes", r"pod", r"ecs", r"eks"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1040",
        technique_name="Network Sniffing",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "CreateTrafficMirrorTarget",
            "CreateTrafficMirrorSession",
            "CreateTrafficMirrorFilter",
        ],
        keywords=["packet", "mirror", "sniff", "capture", "traffic", "network"],
        aws_services=["ec2", "vpc"],
        log_patterns=[r"packet", r"mirror", r"sniff", r"capture"],
        base_confidence=0.7,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1046",
        technique_name="Network Service Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeLoadBalancers",
            "DescribeTargetGroups",
            "DescribeListeners",
            "ListHostedZones",
            "ListResourceRecordSets",
        ],
        keywords=["port", "scan", "service", "endpoint", "load balancer", "dns"],
        aws_services=["elb", "route53"],
        log_patterns=[r"port", r"scan", r"service", r"endpoint"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1018",
        technique_name="Remote System Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeInstances",
            "DescribeInstanceStatus",
            "DescribeAutoScalingGroups",
            "DescribeLaunchTemplates",
        ],
        keywords=["instance", "vm", "ec2", "remote", "host"],
        aws_services=["ec2", "autoscaling"],
        log_patterns=[r"instance", r"vm", r"host"],
        base_confidence=0.6,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1518",
        technique_name="Software Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "ListCommandInvocations",
            "DescribeInstanceInformation",
            "ListComplianceSummaries",
            "DescribeInstancePatches",
        ],
        keywords=["software", "package", "inventory", "installed", "patch"],
        aws_services=["ssm"],
        log_patterns=[r"software", r"package", r"inventory"],
        base_confidence=0.6,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1082",
        technique_name="System Information Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeInstances",
            "DescribeInstanceTypes",
            "DescribeRegions",
            "DescribeAvailabilityZones",
            "GetCallerIdentity",
        ],
        keywords=["system", "info", "machine", "type", "region", "zone"],
        aws_services=["ec2", "sts"],
        log_patterns=[r"system", r"info", r"machine", r"type"],
        base_confidence=0.6,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1016",
        technique_name="System Network Configuration Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeVpcs",
            "DescribeSubnets",
            "DescribeNetworkInterfaces",
            "DescribeSecurityGroups",
            "DescribeRouteTables",
        ],
        keywords=["network", "config", "ip", "address", "dns", "security group"],
        aws_services=["ec2", "vpc"],
        log_patterns=[r"network", r"config", r"ip", r"address"],
        base_confidence=0.6,
        priority=3,
    ),
    TechniqueIndicator(
        technique_id="T1049",
        technique_name="System Network Connections Discovery",
        tactic_id="TA0007",
        tactic_name="Discovery",
        cloudtrail_events=[
            "DescribeVpnConnections",
            "DescribeVpnGateways",
            "DescribeTransitGateways",
            "DescribeVpcPeeringConnections",
            "DescribeDirectConnectGateways",
        ],
        keywords=["connection", "vpn", "tunnel", "peering", "transit"],
        aws_services=["ec2", "directconnect"],
        log_patterns=[r"connection", r"vpn", r"tunnel", r"peering"],
        base_confidence=0.65,
        priority=3,
    ),
]

# Lateral Movement - TA0008
LATERAL_MOVEMENT_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1550.001",
        technique_name="Use Alternate Authentication Material: Application Access Token",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        cloudtrail_events=[
            "AssumeRole",
            "AssumeRoleWithSAML",
            "AssumeRoleWithWebIdentity",
        ],
        keywords=["cross-account", "assume", "lateral", "token"],
        aws_services=["sts"],
        log_patterns=[r"assume", r"lateral", r"cross"],
        base_confidence=0.7,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1021.004",
        technique_name="Remote Services: SSH",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        cloudtrail_events=[
            "SendSSHPublicKey",
            "SendCommand",
            "StartSession",
        ],
        keywords=["ssh", "remote", "key", "session", "connect"],
        aws_services=["ec2-instance-connect", "ssm"],
        log_patterns=[r"ssh", r"remote", r"session"],
        base_confidence=0.7,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1021.007",
        technique_name="Remote Services: Cloud Services",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        cloudtrail_events=[
            "StartSession",
            "SendCommand",
            "RunTask",
            "InvokeFunction",
        ],
        keywords=["ssm", "session", "cloud", "service", "remote", "access"],
        aws_services=["ssm", "ecs", "lambda"],
        log_patterns=[r"session", r"remote", r"service"],
        base_confidence=0.7,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1563.001",
        technique_name="Remote Service Session Hijacking: SSH Hijacking",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        cloudtrail_events=[
            "SendSSHPublicKey",
            "ImportKeyPair",
            "CreateKeyPair",
        ],
        keywords=["ssh", "hijack", "session", "key", "inject"],
        aws_services=["ec2", "ec2-instance-connect"],
        log_patterns=[r"ssh", r"hijack", r"inject"],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1072",
        technique_name="Software Deployment Tools",
        tactic_id="TA0008",
        tactic_name="Lateral Movement",
        cloudtrail_events=[
            "CreateDeployment",
            "UpdateApplication",
            "CreateStack",
            "UpdateStack",
            "StartPipelineExecution",
        ],
        keywords=["deploy", "software", "push", "distribute", "pipeline"],
        aws_services=["codedeploy", "codepipeline", "cloudformation"],
        log_patterns=[r"deploy", r"software", r"push", r"distribute"],
        base_confidence=0.65,
        priority=2,
    ),
]

# Collection - TA0009
COLLECTION_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1530",
        technique_name="Data from Cloud Storage",
        tactic_id="TA0009",
        tactic_name="Collection",
        cloudtrail_events=[
            "GetObject",
            "CopyObject",
            "HeadObject",
            "GetBucketAcl",
        ],
        keywords=[
            "download",
            "exfil",
            "copy",
            "data",
            "s3",
            # MITRE official terms
            "access",
            "retrieve",
            "storage",
            # AWS/CIS terminology
            "public bucket",
            "public access",
            "bucket policy",
            "bucket acl",
        ],
        aws_services=["s3"],
        log_patterns=[
            r"get.*object",
            r"download",
            r"copy",
            r"public.*bucket",
            r"bucket.*policy",
        ],
        base_confidence=0.6,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1119",
        technique_name="Automated Collection",
        tactic_id="TA0009",
        tactic_name="Collection",
        cloudtrail_events=[
            "CreateRule",
            "PutRule",
            "CreateEventSourceMapping",
            "CreateSubscription",
        ],
        keywords=["automated", "scheduled", "collection", "script", "batch"],
        aws_services=["events", "lambda", "sns"],
        log_patterns=[r"automated", r"schedule", r"batch", r"collect"],
        base_confidence=0.6,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1213.003",
        technique_name="Data from Information Repositories: Code Repositories",
        tactic_id="TA0009",
        tactic_name="Collection",
        cloudtrail_events=[
            "GetRepository",
            "ListRepositories",
            "GetBranch",
            "BatchGetRepositories",
        ],
        keywords=["repo", "repository", "code", "source", "codecommit"],
        aws_services=["codecommit"],
        log_patterns=[r"repo", r"repository", r"source", r"code"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1074.002",
        technique_name="Data Staged: Remote Data Staging",
        tactic_id="TA0009",
        tactic_name="Collection",
        cloudtrail_events=[
            "CreateBucket",
            "PutObject",
            "CopyObject",
        ],
        keywords=["staging", "transfer", "copy", "stage", "data"],
        aws_services=["s3"],
        log_patterns=[r"staging", r"transfer", r"stage"],
        base_confidence=0.6,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1560.001",
        technique_name="Archive Collected Data: Archive via Utility",
        tactic_id="TA0009",
        tactic_name="Collection",
        cloudtrail_events=[
            "PutObject",
        ],
        keywords=["archive", "compress", "zip", "tar", "backup"],
        aws_services=["s3"],
        log_patterns=[r"archive", r"compress", r"zip", r"tar"],
        base_confidence=0.6,
        priority=3,
    ),
]

# Exfiltration - TA0010
EXFILTRATION_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1537",
        technique_name="Transfer Data to Cloud Account",
        tactic_id="TA0010",
        tactic_name="Exfiltration",
        cloudtrail_events=[
            "PutBucketPolicy",
            "PutBucketAcl",
            "CopyObject",
            "ModifySnapshotAttribute",
        ],
        keywords=["public", "share", "external", "transfer", "exfil"],
        aws_services=["s3", "ec2", "rds"],
        log_patterns=[r"public", r"share", r"external", r"transfer"],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1567.002",
        technique_name="Exfiltration Over Web Service: Exfiltration to Cloud Storage",
        tactic_id="TA0010",
        tactic_name="Exfiltration",
        cloudtrail_events=[
            "PutObject",
            "CopyObject",
            "CreateMultipartUpload",
        ],
        keywords=["exfil", "upload", "transfer", "cloud", "storage", "export"],
        aws_services=["s3"],
        log_patterns=[r"exfil", r"upload", r"transfer", r"export"],
        base_confidence=0.7,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1048",
        technique_name="Exfiltration Over Alternative Protocol",
        tactic_id="TA0010",
        tactic_name="Exfiltration",
        cloudtrail_events=[
            "CreateHostedZone",
            "ChangeResourceRecordSets",
            "AuthorizeSecurityGroupEgress",
        ],
        keywords=["dns", "tunnel", "alternative", "protocol", "exfil", "covert"],
        aws_services=["route53", "ec2"],
        log_patterns=[r"dns", r"tunnel", r"alternative", r"covert"],
        base_confidence=0.7,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1567",
        technique_name="Exfiltration Over Web Service",
        tactic_id="TA0010",
        tactic_name="Exfiltration",
        cloudtrail_events=[
            "InvokeFunction",
            "Invoke",
        ],
        keywords=["web", "http", "api", "exfil", "external", "upload"],
        aws_services=["lambda", "apigateway"],
        log_patterns=[r"web", r"http", r"api", r"external"],
        base_confidence=0.65,
        priority=2,
    ),
]

# Impact - TA0040
IMPACT_TECHNIQUES = [
    TechniqueIndicator(
        technique_id="T1485",
        technique_name="Data Destruction",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "DeleteBucket",
            "DeleteObject",
            "DeleteObjects",
            "DeleteVolume",
            "DeleteDBInstance",
            "TerminateInstances",
        ],
        keywords=[
            "delete",
            "destroy",
            "terminate",
            "remove",
            "wipe",
            # MITRE official terms
            "erase",
            "purge",
        ],
        aws_services=["s3", "ec2", "rds"],
        log_patterns=[r"delete", r"destroy", r"terminate", r"erase", r"purge"],
        base_confidence=0.75,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1486",
        technique_name="Data Encrypted for Impact",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "PutBucketEncryption",
            "CreateKey",
            "Encrypt",
            "ScheduleKeyDeletion",
        ],
        keywords=["encrypt", "ransom", "kms", "key"],
        aws_services=["kms", "s3"],
        log_patterns=[r"encrypt", r"kms", r"key"],
        base_confidence=0.6,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1496",
        technique_name="Resource Hijacking",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "RunInstances",
            "CreateFunction",
            "UpdateFunctionConfiguration",
        ],
        keywords=["crypto", "mining", "hijack", "resource", "compute"],
        aws_services=["ec2", "lambda"],
        log_patterns=[r"crypto", r"mining", r"unusual.*compute"],
        base_confidence=0.7,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1489",
        technique_name="Service Stop",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "StopInstances",
            "DeleteFunction",
            "DeleteService",
            "DeleteCluster",
            "DeleteDBCluster",
        ],
        keywords=["stop", "disable", "shutdown", "terminate", "suspend"],
        aws_services=["ec2", "lambda", "ecs", "rds"],
        log_patterns=[r"stop", r"disable", r"shutdown", r"suspend"],
        base_confidence=0.7,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1490",
        technique_name="Inhibit System Recovery",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "DeleteSnapshot",
            "DeleteDBSnapshot",
            "DeleteBackup",
            "DeleteRecoveryPoint",
        ],
        keywords=["backup", "snapshot", "recovery", "delete", "destroy"],
        aws_services=["ec2", "rds", "backup"],
        log_patterns=[r"backup", r"snapshot", r"recovery", r"delete"],
        base_confidence=0.8,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1498",
        technique_name="Network Denial of Service",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "DeleteSecurityGroup",
            "AuthorizeSecurityGroupIngress",
            "DeleteSubnet",
        ],
        keywords=["ddos", "dos", "denial", "flood", "network", "attack"],
        aws_services=["ec2", "vpc"],
        log_patterns=[r"ddos", r"dos", r"denial", r"flood"],
        base_confidence=0.7,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1499",
        technique_name="Endpoint Denial of Service",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "ModifyInstanceAttribute",
            "UpdateFunctionConfiguration",
            "PutScalingPolicy",
        ],
        keywords=["dos", "denial", "resource", "exhaust", "overload"],
        aws_services=["ec2", "lambda", "autoscaling"],
        log_patterns=[r"dos", r"denial", r"exhaust", r"overload"],
        base_confidence=0.65,
        priority=2,
    ),
    TechniqueIndicator(
        technique_id="T1531",
        technique_name="Account Access Removal",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "DeleteUser",
            "DeleteRole",
            "DeleteAccessKey",
            "DeactivateMFADevice",
            "RemoveUserFromGroup",
        ],
        keywords=["remove", "delete", "access", "account", "revoke", "lockout"],
        aws_services=["iam"],
        log_patterns=[r"remove", r"delete", r"access", r"revoke", r"lockout"],
        base_confidence=0.8,
        priority=1,
    ),
    TechniqueIndicator(
        technique_id="T1565.001",
        technique_name="Data Manipulation: Stored Data Manipulation",
        tactic_id="TA0040",
        tactic_name="Impact",
        cloudtrail_events=[
            "PutObject",
            "CopyObject",
            "ModifyDBInstance",
        ],
        keywords=["manipulate", "modify", "tamper", "corrupt", "alter"],
        aws_services=["s3", "rds"],
        log_patterns=[r"manipulate", r"modify", r"tamper", r"corrupt"],
        base_confidence=0.65,
        priority=2,
    ),
]

# Combine all technique indicators
TECHNIQUE_INDICATORS: list[TechniqueIndicator] = [
    *RECON_TECHNIQUES,
    *EXECUTION_TECHNIQUES,
    *INITIAL_ACCESS_TECHNIQUES,
    *PERSISTENCE_TECHNIQUES,
    *PRIVILEGE_ESCALATION_TECHNIQUES,
    *DEFENSE_EVASION_TECHNIQUES,
    *CREDENTIAL_ACCESS_TECHNIQUES,
    *DISCOVERY_TECHNIQUES,
    *LATERAL_MOVEMENT_TECHNIQUES,
    *COLLECTION_TECHNIQUES,
    *EXFILTRATION_TECHNIQUES,
    *IMPACT_TECHNIQUES,
]

# Create lookup dictionaries for efficient access
TECHNIQUE_BY_ID: dict[str, TechniqueIndicator] = {
    t.technique_id: t for t in TECHNIQUE_INDICATORS
}

TECHNIQUES_BY_TACTIC: dict[str, list[TechniqueIndicator]] = {}
for t in TECHNIQUE_INDICATORS:
    if t.tactic_id not in TECHNIQUES_BY_TACTIC:
        TECHNIQUES_BY_TACTIC[t.tactic_id] = []
    TECHNIQUES_BY_TACTIC[t.tactic_id].append(t)

CLOUDTRAIL_EVENT_TO_TECHNIQUES: dict[str, list[str]] = {}
for t in TECHNIQUE_INDICATORS:
    for event in t.cloudtrail_events:
        if event not in CLOUDTRAIL_EVENT_TO_TECHNIQUES:
            CLOUDTRAIL_EVENT_TO_TECHNIQUES[event] = []
        CLOUDTRAIL_EVENT_TO_TECHNIQUES[event].append(t.technique_id)
