"""
T1606 - Forge Web Credentials

Adversaries forge web session cookies, SAML tokens, or other authentication
credentials to bypass multi-factor authentication and access web applications.
APT29 used this technique in the SolarWinds compromise.
"""

from .template_loader import (
    RemediationTemplate,
    ThreatContext,
    DetectionStrategy,
    DetectionImplementation,
    DetectionType,
    EffortLevel,
    FalsePositiveRate,
    CloudProvider,
)

TEMPLATE = RemediationTemplate(
    technique_id="T1606",
    technique_name="Forge Web Credentials",
    tactic_ids=["TA0006"],
    mitre_url="https://attack.mitre.org/techniques/T1606/",
    threat_context=ThreatContext(
        description=(
            "Adversaries create fraudulent web credentials including session cookies and "
            "SAML tokens to access web applications and cloud services. Unlike credential "
            "theft, these tokens are newly generated by attackers using stolen secret keys "
            "or signing certificates, allowing them to bypass multi-factor authentication."
        ),
        attacker_goal="Forge authentication credentials to bypass MFA and gain unauthorised access to web applications",
        why_technique=[
            "Bypasses MFA authentication requirements",
            "Tokens appear legitimate to applications",
            "Stolen signing certificates enable persistent access",
            "Forged tokens avoid detection mechanisms",
            "SAML tokens grant access across multiple services",
        ],
        known_threat_actors=[],
        recent_campaigns=[],  # Populated dynamically from MITRE sync data
        prevalence="uncommon",
        trend="increasing",
        severity_score=9,
        severity_reasoning=(
            "This technique completely bypasses MFA controls, which are considered "
            "a critical security measure. Compromised SAML signing certificates enable "
            "broad access across federated services with minimal detection risk."
        ),
        business_impact=[
            "Complete MFA bypass",
            "Unauthorised access to web applications",
            "Persistent access via forged SAML tokens",
            "Difficult to distinguish from legitimate sessions",
            "Potential access to federated cloud services",
        ],
        typical_attack_phase="credential_access",
        often_precedes=["T1078.004", "T1021.007", "T1530"],
        often_follows=["T1552.001", "T1552.004", "T1606"],
    ),
    detection_strategies=[
        # Strategy 1: AWS - SAML Token Anomalies
        DetectionStrategy(
            strategy_id="t1606-aws-saml",
            name="AWS SAML Token Anomaly Detection",
            description="Detect unusual SAML token usage patterns and token forging attempts in AWS.",
            detection_type=DetectionType.CLOUDWATCH_QUERY,
            aws_service="cloudwatch",
            cloud_provider=CloudProvider.AWS,
            implementation=DetectionImplementation(
                query="""fields @timestamp, eventName, sourceIPAddress, userIdentity.principalId, responseElements.assumedRoleUser
| filter eventName = "AssumeRoleWithSAML"
| stats count(*) as auth_count, count_distinct(sourceIPAddress) as unique_ips by userIdentity.principalId, bin(1h)
| filter unique_ips > 3 or auth_count > 50
| sort auth_count desc""",
                cloudformation_template="""AWSTemplateFormatVersion: '2010-09-09'
Description: Detect forged SAML tokens and anomalous federation

Parameters:
  CloudTrailLogGroup:
    Type: String
  AlertEmail:
    Type: String

Resources:
  # Step 1: SNS topic for alerts
  SAMLAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail

  # Step 2: Metric filter for SAML token usage
  SAMLTokenFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref CloudTrailLogGroup
      FilterPattern: '{ $.eventName = "AssumeRoleWithSAML" }'
      MetricTransformations:
        - MetricName: SAMLTokenUsage
          MetricNamespace: Security
          MetricValue: "1"

  # Step 3: Alarm for suspicious SAML activity
  SAMLAnomalyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: SAMLTokenAnomaly
      MetricName: SAMLTokenUsage
      Namespace: Security
      Statistic: Sum
      Period: 300
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

      AlarmActions: [!Ref SAMLAlertTopic]""",
                terraform_template="""# Detect forged SAML tokens and anomalous federation

variable "cloudtrail_log_group" {
  type = string
}

variable "alert_email" {
  type = string
}

# Step 1: SNS topic for alerts
resource "aws_sns_topic" "saml_alerts" {
  name = "saml-token-anomaly-alerts"
  kms_master_key_id = "alias/aws/sns"
}

resource "aws_sns_topic_subscription" "email" {
  topic_arn = aws_sns_topic.saml_alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

# Step 2: Metric filter for SAML token usage
resource "aws_cloudwatch_log_metric_filter" "saml_tokens" {
  name           = "saml-token-usage"
  log_group_name = var.cloudtrail_log_group
  pattern        = "{ $.eventName = \"AssumeRoleWithSAML\" }"

  metric_transformation {
    name      = "SAMLTokenUsage"
    namespace = "Security"
    value     = "1"
  }
}

# Step 3: Alarm for suspicious SAML activity
resource "aws_cloudwatch_metric_alarm" "saml_anomaly" {
  alarm_name          = "SAMLTokenAnomaly"
  metric_name         = "SAMLTokenUsage"
  namespace           = "Security"
  statistic           = "Sum"
  period              = 300
  threshold           = 100
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"

  alarm_actions [aws_sns_topic.saml_alerts.arn]
}""",
                alert_severity="critical",
                alert_title="Suspicious SAML Token Activity Detected",
                alert_description_template="Unusual SAML federation activity detected from {sourceIPAddress}.",
                investigation_steps=[
                    "Review SAML provider configuration in IAM",
                    "Check source IP addresses for anomalies",
                    "Verify SAML assertion attributes and lifetime",
                    "Review assumed role permissions and accessed resources",
                    "Check for impossible travel between authentications",
                ],
                containment_actions=[
                    "Rotate SAML signing certificates immediately",
                    "Revoke active sessions for affected roles",
                    "Review and restrict SAML provider trust policies",
                    "Enable advanced security logging for federation",
                    "Audit all SAML-authenticated access",
                ],
            ),
            estimated_false_positive_rate=FalsePositiveRate.MEDIUM,
            false_positive_tuning="Baseline normal SAML usage patterns from corporate IdP",
            detection_coverage="70% - detects volume anomalies",
            evasion_considerations="Slow, low-volume token usage may evade thresholds",
            implementation_effort=EffortLevel.MEDIUM,
            implementation_time="1-2 hours",
            estimated_monthly_cost="$5-15",
            prerequisites=["CloudTrail logging enabled", "SAML federation configured"],
        ),
        # Strategy 2: AWS - GetFederationToken Abuse
        DetectionStrategy(
            strategy_id="t1606-aws-federation",
            name="AWS Federation Token Abuse Detection",
            description="Detect unauthorised use of GetFederationToken API for credential forging.",
            detection_type=DetectionType.CLOUDWATCH_QUERY,
            aws_service="cloudwatch",
            cloud_provider=CloudProvider.AWS,
            implementation=DetectionImplementation(
                query="""fields @timestamp, eventName, userIdentity.arn, sourceIPAddress, errorCode
| filter eventName = "GetFederationToken"
| stats count(*) as attempts, count_distinct(sourceIPAddress) as unique_ips by userIdentity.arn, bin(6h)
| filter attempts > 10
| sort attempts desc""",
                cloudformation_template="""AWSTemplateFormatVersion: '2010-09-09'
Description: Detect GetFederationToken abuse

Parameters:
  CloudTrailLogGroup:
    Type: String
  AlertEmail:
    Type: String

Resources:
  # Step 1: SNS topic
  FederationAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail

  # Step 2: Metric filter for federation token requests
  FederationTokenFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref CloudTrailLogGroup
      FilterPattern: '{ $.eventName = "GetFederationToken" }'
      MetricTransformations:
        - MetricName: FederationTokenRequests
          MetricNamespace: Security
          MetricValue: "1"

  # Step 3: Alarm for suspicious federation activity
  FederationAbuseAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: FederationTokenAbuse
      MetricName: FederationTokenRequests
      Namespace: Security
      Statistic: Sum
      Period: 21600
      Threshold: 20
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

      AlarmActions: [!Ref FederationAlertTopic]""",
                terraform_template="""# Detect GetFederationToken abuse

variable "cloudtrail_log_group" {
  type = string
}

variable "alert_email" {
  type = string
}

# Step 1: SNS topic
resource "aws_sns_topic" "federation_alerts" {
  name = "federation-token-abuse-alerts"
  kms_master_key_id = "alias/aws/sns"
}

resource "aws_sns_topic_subscription" "email" {
  topic_arn = aws_sns_topic.federation_alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

# Step 2: Metric filter for federation token requests
resource "aws_cloudwatch_log_metric_filter" "federation_tokens" {
  name           = "federation-token-requests"
  log_group_name = var.cloudtrail_log_group
  pattern        = "{ $.eventName = \"GetFederationToken\" }"

  metric_transformation {
    name      = "FederationTokenRequests"
    namespace = "Security"
    value     = "1"
  }
}

# Step 3: Alarm for suspicious federation activity
resource "aws_cloudwatch_metric_alarm" "federation_abuse" {
  alarm_name          = "FederationTokenAbuse"
  metric_name         = "FederationTokenRequests"
  namespace           = "Security"
  statistic           = "Sum"
  period              = 21600
  threshold           = 20
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"

  alarm_actions [aws_sns_topic.federation_alerts.arn]
}""",
                alert_severity="high",
                alert_title="Federation Token Abuse Detected",
                alert_description_template="Unusual GetFederationToken activity from {userIdentity.arn}.",
                investigation_steps=[
                    "Identify the IAM principal making requests",
                    "Review federation token parameters and lifetime",
                    "Check source IPs and geolocations",
                    "Review API calls made with federated credentials",
                    "Verify if legitimate automation or abuse",
                ],
                containment_actions=[
                    "Restrict sts:GetFederationToken permissions",
                    "Revoke compromised IAM credentials",
                    "Implement SCP to limit federation token usage",
                    "Review and reduce federation token lifetime limits",
                    "Enable MFA for sensitive IAM operations",
                ],
            ),
            estimated_false_positive_rate=FalsePositiveRate.LOW,
            false_positive_tuning="Whitelist known automation requiring federation tokens",
            detection_coverage="80% - GetFederationToken is rarely used",
            evasion_considerations="Attackers may use AssumeRole instead",
            implementation_effort=EffortLevel.LOW,
            implementation_time="30-60 minutes",
            estimated_monthly_cost="$3-10",
            prerequisites=["CloudTrail logging enabled"],
        ),
        # Strategy 3: AWS - Cookie Session Anomalies
        DetectionStrategy(
            strategy_id="t1606-aws-session",
            name="AWS Console Session Anomaly Detection",
            description="Detect forged web cookies used for AWS console access.",
            detection_type=DetectionType.CLOUDWATCH_QUERY,
            aws_service="cloudwatch",
            cloud_provider=CloudProvider.AWS,
            implementation=DetectionImplementation(
                query="""fields @timestamp, eventName, userIdentity.principalId, sourceIPAddress, userAgent
| filter eventName = "ConsoleLogin" or eventName = "GetSigninToken"
| stats count(*) as logins, count_distinct(sourceIPAddress) as unique_ips, count_distinct(userAgent) as unique_agents by userIdentity.principalId, bin(1h)
| filter unique_ips > 5 or (logins > 20 and unique_agents > 3)
| sort logins desc""",
                cloudformation_template="""AWSTemplateFormatVersion: '2010-09-09'
Description: Detect forged console session cookies

Parameters:
  CloudTrailLogGroup:
    Type: String
  AlertEmail:
    Type: String

Resources:
  # Step 1: SNS topic
  SessionAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail

  # Step 2: Metric filter for console logins
  ConsoleLoginFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref CloudTrailLogGroup
      FilterPattern: '{ $.eventName = "ConsoleLogin" || $.eventName = "GetSigninToken" }'
      MetricTransformations:
        - MetricName: ConsoleLoginAttempts
          MetricNamespace: Security
          MetricValue: "1"

  # Step 3: Alarm for session anomalies
  SessionAnomalyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ConsoleSessionAnomaly
      MetricName: ConsoleLoginAttempts
      Namespace: Security
      Statistic: Sum
      Period: 300
      Threshold: 30
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

      AlarmActions: [!Ref SessionAlertTopic]""",
                terraform_template="""# Detect forged console session cookies

variable "cloudtrail_log_group" {
  type = string
}

variable "alert_email" {
  type = string
}

# Step 1: SNS topic
resource "aws_sns_topic" "session_alerts" {
  name = "console-session-anomaly-alerts"
  kms_master_key_id = "alias/aws/sns"
}

resource "aws_sns_topic_subscription" "email" {
  topic_arn = aws_sns_topic.session_alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

# Step 2: Metric filter for console logins
resource "aws_cloudwatch_log_metric_filter" "console_logins" {
  name           = "console-login-attempts"
  log_group_name = var.cloudtrail_log_group
  pattern        = "{ $.eventName = \"ConsoleLogin\" || $.eventName = \"GetSigninToken\" }"

  metric_transformation {
    name      = "ConsoleLoginAttempts"
    namespace = "Security"
    value     = "1"
  }
}

# Step 3: Alarm for session anomalies
resource "aws_cloudwatch_metric_alarm" "session_anomaly" {
  alarm_name          = "ConsoleSessionAnomaly"
  metric_name         = "ConsoleLoginAttempts"
  namespace           = "Security"
  statistic           = "Sum"
  period              = 300
  threshold           = 30
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"

  alarm_actions [aws_sns_topic.session_alerts.arn]
}""",
                alert_severity="high",
                alert_title="Console Session Anomaly Detected",
                alert_description_template="Unusual console login patterns detected for {userIdentity.principalId}.",
                investigation_steps=[
                    "Review login timestamps and locations",
                    "Check for impossible travel scenarios",
                    "Verify user agent strings for anomalies",
                    "Review MFA status for login events",
                    "Check for concurrent sessions from different locations",
                ],
                containment_actions=[
                    "Terminate all active console sessions",
                    "Reset user credentials and require password change",
                    "Enable MFA if not already configured",
                    "Review CloudTrail for unauthorised actions",
                    "Implement stricter session timeout policies",
                ],
            ),
            estimated_false_positive_rate=FalsePositiveRate.MEDIUM,
            false_positive_tuning="Account for VPN users and mobile access patterns",
            detection_coverage="65% - focuses on volume and location anomalies",
            evasion_considerations="Sophisticated attackers may mimic legitimate patterns",
            implementation_effort=EffortLevel.MEDIUM,
            implementation_time="1-2 hours",
            estimated_monthly_cost="$5-10",
            prerequisites=["CloudTrail logging enabled"],
        ),
        # Strategy 4: GCP - SAML/OIDC Token Monitoring
        DetectionStrategy(
            strategy_id="t1606-gcp-saml",
            name="GCP SAML/OIDC Token Monitoring",
            description="Detect forged SAML or OpenID Connect tokens in GCP environments.",
            detection_type=DetectionType.CLOUD_LOGGING_QUERY,
            aws_service="n/a",
            gcp_service="cloud_logging",
            cloud_provider=CloudProvider.GCP,
            implementation=DetectionImplementation(
                gcp_logging_query='''protoPayload.methodName=~"google.iam.admin.v1.CreateServiceAccountKey"
OR protoPayload.serviceName="iap.googleapis.com"
OR protoPayload.authenticationInfo.principalEmail=~".*@.*\\.gserviceaccount\\.com"
protoPayload.requestMetadata.callerIp!~"^(10\\.|172\\.|192\\.168)"''',
                gcp_terraform_template="""# GCP: Monitor SAML/OIDC token anomalies

variable "project_id" {
  type = string
}

variable "alert_email" {
  type = string
}

# Step 1: Notification channel
resource "google_monitoring_notification_channel" "email" {
  display_name = "Security Alerts"
  type         = "email"
  labels = {
    email_address = var.alert_email
  }
}

# Step 2: Log-based metric for token anomalies
resource "google_logging_metric" "token_anomaly" {
  name   = "forged-token-detection"
  filter = <<-EOT
    protoPayload.methodName=~"google.iam.admin.v1.CreateServiceAccountKey"
    OR (protoPayload.serviceName="iap.googleapis.com" AND severity>=WARNING)
    OR (protoPayload.authenticationInfo.principalEmail=~".*@.*\\.gserviceaccount\\.com"
        AND protoPayload.requestMetadata.callerIp!~"^(10\\.|172\\.|192\\.168|35\\.)")
  EOT

  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
  }
}

# Step 3: Alert policy
resource "google_monitoring_alert_policy" "token_alert" {
  display_name = "Forged Token Detection"
  combiner     = "OR"

  conditions {
    display_name = "Suspicious token activity"
    condition_threshold {
      filter          = "metric.type=\"logging.googleapis.com/user/${google_logging_metric.token_anomaly.name}\""
      duration        = "300s"
      comparison      = "COMPARISON_GT"
      threshold_value = 20
    }
  }

  notification_channels = [google_monitoring_notification_channel.email.id]
}""",
                alert_severity="critical",
                alert_title="GCP: Forged Token Activity Detected",
                alert_description_template="Suspicious SAML/OIDC token activity detected in project.",
                investigation_steps=[
                    "Review service account key creation events",
                    "Check IAP authentication logs for anomalies",
                    "Verify token issuer and audience claims",
                    "Review source IP addresses and geolocations",
                    "Check for unauthorised Workload Identity usage",
                ],
                containment_actions=[
                    "Delete suspicious service account keys",
                    "Rotate OAuth client secrets",
                    "Review and restrict IAP access policies",
                    "Enable VPC Service Controls",
                    "Audit service account permissions",
                ],
            ),
            estimated_false_positive_rate=FalsePositiveRate.MEDIUM,
            false_positive_tuning="Whitelist known external CI/CD service IPs",
            detection_coverage="75% - detects external token usage",
            evasion_considerations="Attackers using GCP-internal IPs may evade detection",
            implementation_effort=EffortLevel.MEDIUM,
            implementation_time="1-2 hours",
            estimated_monthly_cost="$10-20",
            prerequisites=["Cloud Audit Logs enabled"],
        ),
        # Strategy 5: GCP - Session Cookie Anomalies
        DetectionStrategy(
            strategy_id="t1606-gcp-session",
            name="GCP Console Session Monitoring",
            description="Detect forged session cookies for GCP console access.",
            detection_type=DetectionType.CLOUD_LOGGING_QUERY,
            aws_service="n/a",
            gcp_service="cloud_logging",
            cloud_provider=CloudProvider.GCP,
            implementation=DetectionImplementation(
                gcp_logging_query="""protoPayload.serviceName="login.googleapis.com"
OR protoPayload.methodName=~"google.login.*"
severity>=WARNING""",
                gcp_terraform_template="""# GCP: Monitor console session anomalies

variable "project_id" {
  type = string
}

variable "alert_email" {
  type = string
}

# Step 1: Notification channel
resource "google_monitoring_notification_channel" "email" {
  display_name = "Security Alerts"
  type         = "email"
  labels = {
    email_address = var.alert_email
  }
}

# Step 2: Log-based metric for session anomalies
resource "google_logging_metric" "session_anomaly" {
  name   = "console-session-anomaly"
  filter = <<-EOT
    protoPayload.serviceName="login.googleapis.com"
    OR protoPayload.methodName=~"google.login.*"
    severity>=WARNING
  EOT

  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
  }
}

# Step 3: Alert policy
resource "google_monitoring_alert_policy" "session_alert" {
  display_name = "Console Session Anomaly"
  combiner     = "OR"

  conditions {
    display_name = "Unusual login activity"
    condition_threshold {
      filter          = "metric.type=\"logging.googleapis.com/user/${google_logging_metric.session_anomaly.name}\""
      duration        = "60s"
      comparison      = "COMPARISON_GT"
      threshold_value = 10
    }
  }

  notification_channels = [google_monitoring_notification_channel.email.id]
}""",
                alert_severity="high",
                alert_title="GCP: Console Session Anomaly",
                alert_description_template="Unusual console session activity detected.",
                investigation_steps=[
                    "Review login attempt timestamps and locations",
                    "Check for concurrent sessions from multiple locations",
                    "Verify 2-Step Verification status",
                    "Review Admin Activity logs for suspicious actions",
                    "Check for impossible travel scenarios",
                ],
                containment_actions=[
                    "Revoke all active user sessions",
                    "Reset user passwords",
                    "Enable 2-Step Verification for all users",
                    "Review and restrict access to sensitive resources",
                    "Implement context-aware access policies",
                ],
            ),
            estimated_false_positive_rate=FalsePositiveRate.MEDIUM,
            false_positive_tuning="Baseline normal login patterns and locations",
            detection_coverage="70% - focuses on login anomalies",
            evasion_considerations="Slow session creation may avoid volume thresholds",
            implementation_effort=EffortLevel.MEDIUM,
            implementation_time="1-2 hours",
            estimated_monthly_cost="$10-20",
            prerequisites=[
                "Cloud Audit Logs enabled",
                "Admin Activity logging enabled",
            ],
        ),
    ],
    recommended_order=[
        "t1606-aws-saml",
        "t1606-gcp-saml",
        "t1606-aws-federation",
        "t1606-gcp-session",
        "t1606-aws-session",
    ],
    total_effort_hours=7.5,
    coverage_improvement="+15% improvement for Credential Access tactic",
)
